name: Update Releases List

on:
  workflow_dispatch:

env:
  OUTPUT_PATH: ./.mx/releases_list.json

jobs:
  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Fetch & Generate Releases List
        uses: actions/github-script@v3
        with:
          script: |
            const script = require(`${process.env.GITHUB_WORKSPACE}/.github/update_releases_list.js`);
            await script({github});

      - name: Update Version Compatibility
        run: |
          cd docs/version-compatibility
          node -e "require('./update-versions.js').updateVersionsJson()"

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          commit-message: "[BUILD] Update Release List and Version Compatibility"
          committer: github-action <41898282+github-actions[bot]@users.noreply.github.com>
          author: github-action <41898282+github-actions[bot]@users.noreply.github.com>
          delete-branch: true
          title: "[BUILD] Update Release List and Version Compatibility"
          body: |
            This PR updates:
            - Release list
            - Version compatibility information
          branch: update-releases-list
          branch-suffix: short-commit-hash

      - name: Send Slack Notification
        if: success()
        uses: ./.github/actions/slack-notification
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          message: |
            🚀 *New Native Template Version Released*

            A new version of Native Template has been released with updated version compatibility information.

            Please review the PR for more details: ${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.pr.outputs.pull-request-number }}
